---
- name: Testing rulebook 
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001
  rules:
    - name: Debug variable list
      condition: event.payload is defined
      action:
        debug: 
          msg: "{{ event.payload.path_files }}"
