---
- name: Directory Monitoring 
  hosts: bastion.jferre.local 
  sources:
    - name: file_watch
      ansible.eda.file_watch:
        path: "/tmp/new-files"
        recursive: true
  rules:
    - name: Debug event.payload
      condition: event.payload is defined
      action:
        debug: 
          msg: "{{ event.payload }}"
      
    #- name: DirModifiedEvent
    #  condition: event.type == "DirModifiedEvent"
    #  action:
    #    run_playbook:
    #      name: playbooks/dir-event.yml 
    #    #run_job_template:
    #    #  name: "[EDA] Move files to target directory"
    #    #  organization: Default
    #    #  job_args:
    #    #    #limit: "{{ event.payload.server }}"
    #    #    extra_vars:
    #    #      path_file: "{{ event.payload.path_files }}"
    #- name: FileModifiedEvent
    #  condition: event.type == "FileModifiedEvent"
    #  action:
    #    run_playbook:
    #      name: playbooks/file-event.yml 
    #    #run_job_template:
    #    #  name: "[EDA] Move files to target directory"
    #    #  organization: Default
    #    #  job_args:
    #    #    #limit: "{{ event.payload.server }}"
    #    #    extra_vars:
    #    #      path_file: "{{ event.payload.path_files }}"
