---
- name: Monitor critical configuration file
  hosts: zbx01 
  sources:
    - name: File watch
      ansible.eda.file_watch:
        path: "/tmp/new-files"
        recursive: true
  rules:
    - name: DirModifiedEvent 
      condition: event.type == "DirModifiedEvent"
      action:
        debug:
    - name: FileModifiedEvent
      condition: event.type == "FileModifiedEvent"
      action:
        debug:
