---
- name: Monitor critical configuration file
  hosts: localhost
  sources:
    - name: File watch
      ansible.eda.file_watch:
        path: "/tmp/new-files"
        recursive: true
  rules:
    - name: Trigger playbook on config change
      condition: event.type == "DirModifiedEvent"
      action:
        debug:
    - name: FileModifiedEvent
      condition: event.type == "FileModifiedEvent"
      action:
        debug:
