---
- hosts: all
  gather_facts: false
  tasks:
    - name: Copy files to /tmp/files-moved
      ansible.builtin.copy:
        src: /tmp/new-files/
        remote_src: true
        dest: /tmp/files-moved
        mode: "0644"
        unsafe_writes: no

    - name: Localizar arquivos no diretório de origem
      ansible.builtin.find:
        paths: /tmp/new-files/
        file_type: file
      register: files_found

    - name: Remove files from source directory
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ files_found.files }}"
