---
- hosts: all
  gather_facts: false
  tasks:
    - name: Copy files to /tmp/files-moved
      ansible.builtin.copy:
        src: "{{ path_file }}"
        remote_src: true
        dest: /tmp/files-moved/
        mode: "0644"
        unsafe_writes: no

    - name: Remove files from source directory
      ansible.builtin.file:
        path: "{{ path_file }}"
        state: absent
